Microserve.Web/Controllers/AuthenticationController.cs
using Microserve.Web.Models.DTOs.RequestDtos;
using Microserve.Web.Models.DTOs.ResponseDtos;
using Microserve.Web.Services.IService;
using Microserve.Web.Utility;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace Microserve.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthWebService _authWebService;
        private readonly ITokenProvider _tokenProvider;
        public AuthenticationController(IAuthWebService authWebService, ITokenProvider tokenProvider)
        {
            _authWebService = authWebService;
            _tokenProvider = tokenProvider; 

        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
           
            return View();
        } 
        
        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO loginRequestDTO = new();
            return View(loginRequestDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO loginRequestDTO)
        {

            ResponseDto responseDto = await _authWebService.LoginAsync(loginRequestDTO);
            if(responseDto != null && responseDto.IsSuccess)
            {
                //if login was successful deserizalize the loginResponseDTO to get the result
                LoginResponseDTO loginResponseDTO = JsonConvert.DeserializeObject<LoginResponseDTO?>(Convert.ToString(responseDto.Result));
                //sign in user
                await SignInUserAsync(loginResponseDTO);
                //set the cookie with token 
                _tokenProvider.setToken(loginResponseDTO.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //return error if there is any
                ModelState.AddModelError("CustomError", responseDto.Message);
                //return back with view with login request data and the error
                return View(loginRequestDTO);
            }

        }


        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=StaticDetails.RoleAdmin, Value=StaticDetails.RoleAdmin},
                new SelectListItem {Text=StaticDetails.RoleCustomer, Value=StaticDetails.RoleCustomer},

            };
            ViewBag.RoleList = roleList;

            RegistrationRequestDTO registrationRequestDTO = new();
            return View(registrationRequestDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationRequestDTO obj)

        {
            //if the model state is invalid, return to the view and repopulate the roles 
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=StaticDetails.RoleAdmin, Value=StaticDetails.RoleAdmin},
                new SelectListItem {Text=StaticDetails.RoleCustomer, Value=StaticDetails.RoleCustomer},

            };
            ViewBag.RoleList = roleList;

           //make a call to register api endpoint
            ResponseDto result = await _authWebService.RegisterAsync(obj);
            //create assign role response varible
            ResponseDto assignRole;
            ResponseDto error;
            if (result != null && result.IsSuccess)
            {
                //if the form request didnt supply role, set defult to customer
                if (string.IsNullOrEmpty(obj.Role))
                {
                    // set defult to customer
                    obj.Role = StaticDetails.RoleCustomer;
                }
                //call the create role api endpoint
                assignRole = await _authWebService.AssignRoleAsync(obj);
                if (assignRole != null && assignRole.IsSuccess)
                {
                    //if assigned a role, then return to login page with message
                    TempData["success"] = "You haver registered successfully!";
                    return RedirectToAction(nameof(Login));
                }

            }
            else
            {
                TempData["error"] = result!.Message;
            }
           
            return View(obj);
            
           
        }

   
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.clearToken();
            TempData["success"] = "You have successfully logged out of the system!";
            return RedirectToAction("Index", "Home");
        }


        private async Task SignInUserAsync(LoginResponseDTO model)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwt = handler.ReadJwtToken(model.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            //retrive role

            identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));


            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

Microserve.Web/Controllers/LocatorController.cs
using Microserve.Services.AuthAPI.Data;
using Microserve.Web.Helpers;
using Microserve.Web.Models.DTOs;
using Microserve.Web.Models.DTOs.ResponseDtos;
using Microserve.Web.Services.IService;
using Microserve.Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection.Metadata.Ecma335;

namespace Microserve.Web.Controllers
{
    public class LocatorController : Controller
    {
        private readonly ILocatorService _locatorService;
        private readonly IAuthWebService _authWebService;
        public LocatorController(ILocatorService locatorService, IAuthWebService authWebService)
        {
            _locatorService = locatorService;
            _authWebService = authWebService;
        }

        [HttpGet]
        public async Task<IActionResult> FacilityIndex()
        {

            try
            {
                List<ResultDTO> list = new();
                ResponseDto? response = await _locatorService.GetAllFacilitiesAsync();
                if (response != null && response.IsSuccess)
                {
                    list = JsonConvert.DeserializeObject<List<ResultDTO>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["warning"] = response.Message;
                }

                return View(list);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
                return View();
            }
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> ListFacilities()
        {

            try
            {
                List<ResultDTO> list = new();
                ResponseDto? response = await _locatorService.GetAllFacilitiesAsync();
                if (response != null && response.IsSuccess)
                {
                    list = JsonConvert.DeserializeObject<List<ResultDTO>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["warning"] = response.Message;
                }

                return View(list);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
                return View();
            }
        }
        public async Task<IActionResult> ViewMap(int Id)
        {

            try
            {
                ResponseDto? response = await _locatorService.ViewMapData(Id);
                if (response != null && response.IsSuccess)
                {
                   var list = JsonConvert.DeserializeObject<ResultDTO>(Convert.ToString(response.Result));
                    return View(list);

                }
                else
                {
                    TempData["warning"] = response.Message;
                    return RedirectToAction("FacilityIndex");
                }

            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Search(string Name, string State, string LGA)
        {
            try
            {
                if(string.IsNullOrWhiteSpace(Name) && string.IsNullOrWhiteSpace(LGA) && string.IsNullOrWhiteSpace( State))
                {
                    TempData["error"] = "Please search by state, lga or name of the facility";
                    return RedirectToAction(nameof(FacilityIndex));
                }

                List<ResultDTO> list = new();
                SearchDTO searchDTO = new SearchDTO
                {
                    Name = Name,
                    LGA = LGA,
                    State = State
                };
                ResponseDto? response = await _locatorService.SearchFacilityAsync(searchDTO);
                if (response != null && response.IsSuccess)
                {
                    list = JsonConvert.DeserializeObject<List<ResultDTO>>(Convert.ToString(response.Result));
                }
                else
                {
                    TempData["warning"] = response.Message;
                }


                return View("FacilityIndex", list);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
                return View();
            }
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult FacilityCreate()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult>FacilityCreate(LocatorDTO model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
               
                ResponseDto? response = await _locatorService.CreateLocationAsync(model);
                TempData["success"] = "Facility Created successfully";
                return RedirectToAction(nameof(FacilityCreate));
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
                return View(model);
            }
        }

 
        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> FacilityDelete(int Id)
        {

            ResponseDto? response = await _locatorService.DeleteLocationAsync(Id);
            if (response != null && response.IsSuccess)
            {
                TempData["info"] = "Facility Deleted!";
                return RedirectToAction(nameof(ListFacilities));

            }
            return View("ListFacilities");

        }
        
        
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> FacilityUpdate(int Id)
        {
            
            ResponseDto? response = await _locatorService.GetFacilityByIdAsync(Id);
            if (response != null && response.IsSuccess)
            {
                LocatorDTO? model = JsonConvert.DeserializeObject<LocatorDTO>(Convert.ToString(response.Result));
                return View(model);

            }
            return NotFound();
           
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> FacilityUpdate(LocatorDTO locatorDTO)
        {

            ResponseDto? response = await _locatorService.UpdateAsync(locatorDTO);
            if (response != null && response.IsSuccess)
            {
                TempData["info"] = "Facility Updated!";
                return RedirectToAction(nameof(ListFacilities));

            }
            return View(locatorDTO);

        }

    }
}

Microserve.Web/Views/Authentication/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<h1>Access Denied</h1>

<div class="alert alert-danger text-center">
    <h4>Access Denied</h4>
    <p>You do not have permission to access this page.</p>
    <a href="@Url.Action("FacilityIndex", "Locator")" class="btn btn-primary">Return to List of Facilities</a>
</div>

Microserve.Web/Views/Authentication/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Dashboard

Microserve.Web/Views/Authentication/Login.cshtml
@model LoginRequestDTO

<form method="post">
    <div class="container border p-4">
        <div class="row text-center">
            <h3>Login</h3>
        </div>
        
        <div class="row">
            <div class="col-6 offset-3 pb-2">
                <input asp-for="UserName" class="form-control" placeholder="Username" />
                <span class="text-danger" asp-validation-for="UserName"></span>
            </div>
            <div class="col-6 offset-3 pb-2">
                <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-6 offset-3 pb-2">
                <button type="submit" class="btn btn-info btn-block">Login</button>
            </div>
            <div class="col-6 offset-3 pb-2">
               Don't have an account? <a asp-controller="Authentication" asp-action="Register">Register</a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Microserve.Web/Views/Authentication/Register.cshtml
@model RegistrationRequestDTO

<form method="post">
    <div class="container border p-4">
        <div class="row text-center">
            <h3>Register</h3>
        </div>
        <div class="row" asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="col-6 offset-3 pb-2">
                <input asp-for="Name" class="form-control" placeholder="Fullname" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="col-6 offset-3 pb-2">
                <input asp-for="Email" class="form-control" placeholder="Email address" />
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>
            <div class="col-6 offset-3 pb-2">
                <input asp-for="PhoneNumber" class="form-control" placeholder="PhoneNumber" />
                <span class="text-danger" asp-validation-for="PhoneNumber"></span>
            </div>

            <div class="col-6 offset-3 pb-2">
                <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>
            <div class="col-6 offset-3 pb-2">
                <select asp-for="Role" class="form-select" asp-items="@ViewBag.RoleList">
                    <option value="">--Select Role--</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-6 offset-3 pb-2">
                <button type="submit" class="btn btn-primary btn-block">Register</button>
            </div>
            <div class="col-6 offset-3 pb-2">
                Already have an account? <a asp-controller="Authentication" asp-action="Login">Login</a>
            </div>
        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}